export default {
    'app.content': 'Content',
    'app.info': 'Info',
    'app.name': 'Name',
    'app.created': 'Created by',
    'app.createdDate': 'Created date',
    'app.selectDefaultTemplate': 'Select default template*',
    'app.addExistingContent': 'Add existing content',
    'app.addNewContent': 'Add new content',
    'app.selectContent': 'Select Content',
    'app.select': 'Select',
    'app.selectCollection': 'Select Collection Type',
    'app.chooseAnOption': 'Choose an option',
    'app.widgetConfiguration': 'Widget Configuration',
    'app.queryFilter': 'Query Filter',
    'app.cancel': 'Cancel',
    'app.saveAsQuery': 'Save as Query',
    'app.saveAsListOfContents': 'Save as list of Contents',
    'app.search': 'Search',
    'app.lastEdited': 'Last edited',
    'app.result': 'Result',
    'app.remove': 'Remove',
    'app.query': 'Query',
    'app.selectTemplate': 'Select Template',
    'app.save': 'Save',
    'app.edit': 'Edit content',
    'app.noMatchesFound': 'No matches found',
    'app.noDataAvailable': 'No data available',
    'app.firstPage': 'First Page',
    'app.previousPage': 'Previous Page',
    'app.currentPage': 'Current Page',
    'app.nextPage': 'Next Page',
    'app.lastPage': 'Last Page',
    'app.perPage': 'per page',
    'app.of': 'of',
    'app.ok':'Ok'
}