export default {
    'app.content': 'Contenuto',
    'app.info': 'Informazioni',
    'app.name': 'Nome',
    'app.created': 'Creata da',
    'app.createdDate': 'Data di Creazione',
    'app.selectDefaultTemplate': 'Seleziona il modello predefinito*',
    'app.addExistingContent': 'Aggiungi contenuto esistente',
    'app.addNewContent': 'Aggiungi nuovo contenuto',
    'app.selectContent': 'Seleziona Contenuto',
    'app.select': 'Selezionare',
    'app.selectCollection': 'Seleziona Tipo di raccolta',
    'app.chooseAnOption': `Scegliere un'opzione`,
    'app.widgetConfiguration': 'Widget Configuration',
    'app.queryFilter': 'Filtro di query',
    'app.cancel': 'Annulla',
    'app.saveAsQuery': 'Salva come query',
    'app.saveAsListOfContents': 'Salva come elenco di contenuti',
    'app.search': 'Ricerca',
    'app.lastEdited': 'Ultima modifica',
    'app.result': 'Risultato',
    'app.remove': 'Rimuovere',
    'app.query': 'Domanda',
    'app.selectTemplate': 'Seleziona Modello',
    'app.save': 'Salva',
    'app.edit': 'Modifica contenutoe',
    'app.noMatchesFound': 'Nessun risultato trovato',
    'app.noDataAvailable': 'Nessun dato disponibile',
    'app.firstPage': 'Prima pagina',
    'app.previousPage': 'Pagina precedente',
    'app.currentPage': 'Pagina corrente',
    'app.nextPage': 'Pagina successiva',
    'app.lastPage': 'Ultima pagina',
    'app.perPage': 'per pagina',
    'app.of': 'di',
    'app.ok':'Ok'

}